apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: spc-myk8skv
spec:
  provider: azure
  secretObjects:
  - secretName: test-secret
    data:
    - key: key
      objectName: ExamplePassword
    type: Opaque
  parameters:
    usePodIdentity: "true"                                      
    useVMManagedIdentity: "false"                               
    userAssignedIdentityID: ""                                                                                                
    keyvaultName: "mjtsk8skv"                                                                
    cloudName: ""                                               
    objects:  |
      array:
        - |
          objectName: ExamplePassword                              
          objectType: secret                                    
          objectVersion: ""                                     
    resourceGroup: "aks2akvrg"                      
    subscriptionId: "6fec89d4-ab6b-4f59-bf4f-52ba18d6e472"      
    tenantId: "f1341b29-2fcf-4b79-89cc-cd1c3af0c533" 
